#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/724f0405-b8b5-4d24-8f8d-ed6d5319df46 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSwitch l1;
  CloudSwitch l2;
  CloudSwitch l3;
  CloudSwitch l4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  pinMode(16,OUTPUT);
  pinMode(5,OUTPUT);
  pinMode(14,OUTPUT);
  pinMode(12,OUTPUT);
  
  digitalWrite(16,HIGH);
  digitalWrite(5,HIGH);
  digitalWrite(22,HIGH);
  digitalWrite(23,HIGH);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(100); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}


/*
  Since L1 is READ_WRITE variable, onL1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onL1Change()  {
  // Add your code here to act upon L1 change
  if(l1)
  {
    digitalWrite(16,false);
  }
  else
  {
    digitalWrite(16,true);
  }
}

/*
  Since L2 is READ_WRITE variable, onL2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onL2Change()  {
  // Add your code here to act upon L2 change
   if(l2)
  {
    digitalWrite(5,LOW);
  }
  else
  {
    digitalWrite(5,HIGH);
  }
}




/*
  Since L3 is READ_WRITE variable, onL3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onL3Change()  {
  // Add your code here to act upon L3 change
   if(l3)
  {
    digitalWrite(12,LOW);
  }
  else
  {
    digitalWrite(12,HIGH);
  }
}

/*
  Since L4 is READ_WRITE variable, onL4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onL4Change()  {
  // Add your code here to act upon L4 change
   if(l4)
  {
    digitalWrite(14,LOW);
  }
  else
  {
    digitalWrite(14,HIGH);
  }
}





